### ISSUE TITLE
https://matcher.wavesplatform.com/api/v2 is dead

### ISSUE THREAD

**Issue by loxal** [wavesplatform/swagger-api-design#2]
https://matcher.wavesplatform.com/api/v2 is not available. Also where can I find the WAVES reference API specification? The broken URL is mentioned here https://github.com/wavesplatform/swagger-api-design/blob/master/matcher.v2.yaml

**Comment by xenohunter** [comment]
Hello! This is a design repository and almost none of the methods mentioned here are available. You can find the actual API specifications [here](https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API).

**Comment by loxal** [comment]
@xenohunter Unfortunately https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API does not contain any specific server that exposes this API which is a nice thing when somebody wants to actually try out something. I am sure I am not the only one who look for a specific reference server that runs the latest node software. 

So this repo seems to be a working draft of the next-gen WAVES API, aka v2? It would be great if the v1 APIs would be available as Swagger/RAML specifications as well so one could just feed them to a REST client instead of carefully assembling the calls that are described at https://github.com/wavesplatform/Waves/wiki/Waves-Node-REST-API

**Comment by xenohunter** [comment]
@loxal ah, I understand. There is a server providing API both for mainnet (https://nodes.wavesnodes.com) and testnet (https://testnet1.wavesnodes.com). The second one provides Swagger docs, and the first one works only with exact API routes (e.g. https://nodes.wavesnodes.com/blocks/height).

You also could make use of this JS library, [waves-api](https://github.com/xenohunter/waves-api) which wraps all the cryptography complexity.
